package com.sforce.soap.enterprise.sobject;

/**
 * This is a generated class for the SObject Enterprise API.
 * Do not edit this file, as your changes will be lost.
 */
public class Contact extends com.sforce.soap.enterprise.sobject.SObject {

    /**
     * Constructor
     */
    public Contact() {}

    /* Cache the typeInfo instead of declaring static fields throughout*/
    private transient java.util.Map<String, com.sforce.ws.bind.TypeInfo> typeInfoCache = new java.util.HashMap<String, com.sforce.ws.bind.TypeInfo>();
    private com.sforce.ws.bind.TypeInfo _lookupTypeInfo(String fieldName, String namespace, String name, String typeNS, String type, int minOcc, int maxOcc, boolean elementForm) {
      com.sforce.ws.bind.TypeInfo typeInfo = typeInfoCache.get(fieldName);
      if (typeInfo == null) {
        typeInfo = new com.sforce.ws.bind.TypeInfo(namespace, name, typeNS, type, minOcc, maxOcc, elementForm);
        typeInfoCache.put(fieldName, typeInfo);
      }
      return typeInfo;
    }

  /**
   * element : Account of type {urn:sobject.enterprise.soap.sforce.com}Account
   * java type: com.sforce.soap.enterprise.sobject.Account
   */
  private boolean Account__is_set = false;

  private com.sforce.soap.enterprise.sobject.Account Account;

  public com.sforce.soap.enterprise.sobject.Account getAccount() {
    return Account;
  }

  public void setAccount(com.sforce.soap.enterprise.sobject.Account Account) {
    this.Account = Account;
    Account__is_set = true;
  }

  protected void setAccount(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __in.peekTag();
    if (__typeMapper.isElement(__in, _lookupTypeInfo("Account", "urn:sobject.enterprise.soap.sforce.com","Account","urn:sobject.enterprise.soap.sforce.com","Account",0,1,true))) {
      setAccount((com.sforce.soap.enterprise.sobject.Account)__typeMapper.readObject(__in, _lookupTypeInfo("Account", "urn:sobject.enterprise.soap.sforce.com","Account","urn:sobject.enterprise.soap.sforce.com","Account",0,1,true), com.sforce.soap.enterprise.sobject.Account.class));
    }
  }

  private void writeFieldAccount(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
    __typeMapper.writeObject(__out, _lookupTypeInfo("Account", "urn:sobject.enterprise.soap.sforce.com","Account","urn:sobject.enterprise.soap.sforce.com","Account",0,1,true), Account, Account__is_set);
  }

  /**
   * element : AccountId of type {urn:enterprise.soap.sforce.com}ID
   * java type: java.lang.String
   */
  private boolean AccountId__is_set = false;

  private java.lang.String AccountId;

  public java.lang.String getAccountId() {
    return AccountId;
  }

  public void setAccountId(java.lang.String AccountId) {
    this.AccountId = AccountId;
    AccountId__is_set = true;
  }

  protected void setAccountId(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __in.peekTag();
    if (__typeMapper.isElement(__in, _lookupTypeInfo("AccountId", "urn:sobject.enterprise.soap.sforce.com","AccountId","urn:enterprise.soap.sforce.com","ID",0,1,true))) {
      setAccountId(__typeMapper.readString(__in, _lookupTypeInfo("AccountId", "urn:sobject.enterprise.soap.sforce.com","AccountId","urn:enterprise.soap.sforce.com","ID",0,1,true), java.lang.String.class));
    }
  }

  private void writeFieldAccountId(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
    __typeMapper.writeObject(__out, _lookupTypeInfo("AccountId", "urn:sobject.enterprise.soap.sforce.com","AccountId","urn:enterprise.soap.sforce.com","ID",0,1,true), AccountId, AccountId__is_set);
  }

  /**
   * element : FirstName of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private boolean FirstName__is_set = false;

  private java.lang.String FirstName;

  public java.lang.String getFirstName() {
    return FirstName;
  }

  public void setFirstName(java.lang.String FirstName) {
    this.FirstName = FirstName;
    FirstName__is_set = true;
  }

  protected void setFirstName(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __in.peekTag();
    if (__typeMapper.isElement(__in, _lookupTypeInfo("FirstName", "urn:sobject.enterprise.soap.sforce.com","FirstName","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
      setFirstName(__typeMapper.readString(__in, _lookupTypeInfo("FirstName", "urn:sobject.enterprise.soap.sforce.com","FirstName","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
    }
  }

  private void writeFieldFirstName(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
    __typeMapper.writeObject(__out, _lookupTypeInfo("FirstName", "urn:sobject.enterprise.soap.sforce.com","FirstName","http://www.w3.org/2001/XMLSchema","string",0,1,true), FirstName, FirstName__is_set);
  }

  /**
   * element : LastName of type {http://www.w3.org/2001/XMLSchema}string
   * java type: java.lang.String
   */
  private boolean LastName__is_set = false;

  private java.lang.String LastName;

  public java.lang.String getLastName() {
    return LastName;
  }

  public void setLastName(java.lang.String LastName) {
    this.LastName = LastName;
    LastName__is_set = true;
  }

  protected void setLastName(com.sforce.ws.parser.XmlInputStream __in,
      com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException, com.sforce.ws.ConnectionException {
    __in.peekTag();
    if (__typeMapper.isElement(__in, _lookupTypeInfo("LastName", "urn:sobject.enterprise.soap.sforce.com","LastName","http://www.w3.org/2001/XMLSchema","string",0,1,true))) {
      setLastName(__typeMapper.readString(__in, _lookupTypeInfo("LastName", "urn:sobject.enterprise.soap.sforce.com","LastName","http://www.w3.org/2001/XMLSchema","string",0,1,true), java.lang.String.class));
    }
  }

  private void writeFieldLastName(com.sforce.ws.parser.XmlOutputStream __out, com.sforce.ws.bind.TypeMapper __typeMapper) throws java.io.IOException {
    __typeMapper.writeObject(__out, _lookupTypeInfo("LastName", "urn:sobject.enterprise.soap.sforce.com","LastName","http://www.w3.org/2001/XMLSchema","string",0,1,true), LastName, LastName__is_set);
  }
}
